name: Cross Platform Import
on: [pull_request]

jobs:
  build:
    name: Module imports on all platforms
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Perform the import
      shell: pwsh
      run: Import-Module ./dbatools.psd1 -ErrorAction Stop; (Get-DbaManagementObject).LoadTemplate -ne $null
