
-- EXEC  USP_RS_GET_SERVER_SPACE 'Server'

USE DBA_REPORT_CODE
GO


ALTER PROC USP_RS_GET_DISKSPACE_DRIVE_ALONE

( @SERVERNAME VARCHAR(50),@DISK VARCHAR(50)
) 
AS

BEGIN


SELECT TOP 10  DRIVE,FREE_SPACE_IN_MB,UPLOAD_DATE FROM [DBADATA_ARCHIVE]..[DBA_ALL_SERVER_SPACE]
WHERE SERVER_NAME LIKE @SERVERNAME AND DRIVE LIKE @DISK 
ORDER BY UPLOAD_DATE DESC

END

/*
SELECT TOP 25 * FROM [DBADATA_ARCHIVE]..[DBA_ALL_SERVER_SPACE]
WHERE SERVER_NAME LIKE 'Server' AND DRIVE LIKE 'C' 
ORDER BY UPLOAD_DATE DESC

*/