use DBA_Report_Code
go
alter procedure [dbo].[Usp_Space_Percentage_ALL_Trends]
(@Server varchar(500),@Drive varchar(10))
as
begin


SELECT SERVER_NAME,
AVG(FREE_SPACE_IN_MB) AS FREE_SPACE_IN_MB,
AVG (USED_SPACE_IN_MB) AS USED_SPACE_IN_MB,
AVG(TOTAL_SPACE_IN_MB) AS TOTAL_SPACE_IN_MB,
PRECENTAGE_FREE As Percentage_Free,
DRIVE,CAST(T.UPLOAD_DATE AS DATE) AS DATE

FROM
DBADATA_ARCHIVE.[DBO].DBA_ALL_SERVER_SPACE_PERCENTAGE T 
WHERE SERVER_NAME =  @SERVER AND DRIVE=@DRIVE
AND UPLOAD_DATE >= GETDATE ()-120
GROUP BY CAST(T.UPLOAD_DATE AS DATE),PRECENTAGE_FREE,SERVER_NAME,DRIVE
ORDER BY CAST(T.UPLOAD_DATE AS DATE) ASC;

end

-- select * from DBADATA_ARCHIVE.[dbo].[DBA_All_Server_Space_percentage] where SERVER_NAME ='Server'

-- EXEC [USP_SPACE_PERCENTAGE_ALL_TRENDS] 'Server','D'
/*

select *
from
DBAdata_Archive.[dbo].[DBA_All_Server_Space_percentage] t 
where SERVER_NAME= 'Server' 
and drive ='E'
and Upload_date >= getdate ()-300
order by Upload_date desc




SELECT SERVER_NAME,
AVG(FREE_SPACE_IN_MB) AS FREE_SPACE_IN_MB,
AVG (USED_SPACE_IN_MB) AS USED_SPACE_IN_MB,
AVG(TOTAL_SPACE_IN_MB) AS TOTAL_SPACE_IN_MB,
PRECENTAGE_FREE As Percentage_Free,
DRIVE,CAST(T.UPLOAD_DATE AS DATE) AS DATE

FROM
DBADATA_ARCHIVE.[DBO].DBA_ALL_SERVER_SPACE_PERCENTAGE T 
WHERE SERVER_NAME =  'Server' AND DRIVE='D'
AND UPLOAD_DATE >= GETDATE ()-120
GROUP BY CAST(T.UPLOAD_DATE AS DATE),PRECENTAGE_FREE,SERVER_NAME,DRIVE
ORDER BY CAST(T.UPLOAD_DATE AS DATE) ASC;

*/